apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ks-go-sample
  name: ks-go-sample
  namespace: bank
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubesphere
    component: ks-go-sample
    tier: backend
  sessionAffinity: None
  type: NodePort
