apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: ks-go-sample
    tier: backend
  name: ks-go-sample
  namespace: bank
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: ks-go-sample
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: ks-go-sample
        tier: backend
    spec:
      containers:
      - image: $DOCKER_REPO_ADDRESS/$DOCKER_REPO_NAMESPACE/$APP_NAME:$BUILD_NUMBER
        imagePullPolicy: Always
        name: ks-go
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
